
package com.project.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerInfo", targetNamespace = "http://ws.project.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerInfo {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerName", targetNamespace = "http://ws.project.com/", className = "com.project.ws.GetServerName")
    @ResponseWrapper(localName = "getServerNameResponse", targetNamespace = "http://ws.project.com/", className = "com.project.ws.GetServerNameResponse")
    @Action(input = "http://ws.project.com/ServerInfo/getServerNameRequest", output = "http://ws.project.com/ServerInfo/getServerNameResponse")
    public String getServerName();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://ws.project.com/", className = "com.project.ws.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://ws.project.com/", className = "com.project.ws.DivisionResponse")
    @Action(input = "http://ws.project.com/ServerInfo/divisionRequest", output = "http://ws.project.com/ServerInfo/divisionResponse")
    public int division(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
